### ISSUE TITLE
getBoundingRect fails for nested Instance nodes with rotated children

### ISSUE THREAD

**Issue by oisinlavery** [figma-plugin-helper-functions/figma-plugin-helpers#44]
This method fails for nested instance nodes which have rotated children. It is not possible to add the group to the instance.

`in group: group() failed: Cannot move node. New parent is an instance or is inside of an instance`

![Screen Shot 2020-05-12 at 11 34 45 AM](https://user-images.githubusercontent.com/1757344/81675228-62892c80-9446-11ea-84a7-aaff1a84119c.png)

**Comment by alexandrtovmach** [comment]
@Andreslav It's your helper, could you take a look?

**Comment by Andreslav** [comment]
@oisinlavery, hello!
Can you test? [Helper update get bounding rect](https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/pull/54)

**Comment by alexandrtovmach** [comment]
Fix released in v0.13.1
If issue still exist, feel free to reopen this issue

**Comment by oisinlavery** [comment]
sorry for the delay in responding...

This is a great improvement over the group solution, however still having issues with rotated descendants.

I've attached an example fig file, run getBoundingRect on the rotated pieces of the icon and you will get incorrect values for x and y (width and height seems correct).

[getBoundingRect test.fig.zip](https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/files/4926998/getBoundingRect.test.fig.zip)

**Comment by oisinlavery** [comment]
@alexandrtovmach I can't reopen this issue - would you mind doing so :)

**Comment by Andreslav** [comment]
@oisinlavery Yes, I saw it and fixed it. Thank.

Check out https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/pull/60

**Comment by oisinlavery** [comment]
I can confirm this is working as expected now. 
Thanks for fixing this so quickly, amazing work.
