### ISSUE TITLE
getBoundingRect returns incorrect Rect when Node has been flipped / reversed

### ISSUE THREAD

**Issue by oisinlavery** [figma-plugin-helper-functions/figma-plugin-helpers#64]
<img width="1145" alt="Screen Shot 2020-07-23 at 4 10 49 PM" src="https://user-images.githubusercontent.com/1757344/88303911-7d5a0600-ccff-11ea-8785-e03cbc064976.png">

The containing FrameNode is at [0,0]
The TextNode is reversed and getBoundingRect incorrectly reports y = 42

**Comment by Andreslav** [comment]
@oisinlavery Hey. Can you provide a link to the file with the problem?

**Comment by oisinlavery** [comment]
Hey Andre, sure thing:
https://www.figma.com/file/fgQkqkQzXz5mmyH6Oi0Idn/getBoundingRect-test?node-id=5%3A2

"G - flipped" and "Red - not flipped" should have the same bounding rect but the y values are not the same.

**Comment by Andreslav** [comment]
I don't know how to fix it yet (

**Comment by oisinlavery** [comment]
Do you think it's a trigonometry issue or a Figma data issue?

**Comment by Andreslav** [comment]
Trigonometry. I seem to have figured out what to do.

**Comment by Andreslav** [comment]
@oisinlavery  It works for me!
https://github.com/figma-plugin-helper-functions/figma-plugin-helpers/blob/Fixing-getBoundingRect/src/helpers/getBoundingRect.ts

**Comment by oisinlavery** [comment]
sweet, I'll test it out first thing tomorrow.

**Comment by oisinlavery** [comment]
I can confirm that this is working well now. Thanks for fixing so quickly Andreslav.
